# This is a `composite` action which allows us to reuse multiple steps into different jobs.
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

name: Install Dependencies
description: Install Dependencies
runs:
  using: composite
  steps:
    - name: Set nodejs version according to '.nvmrc'
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install Dependencies
      run: npm ci --prefer-offline --ignore-scripts --no-audit --no-fund --install-strategy=linked
      shell: bash
