# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Bouncer

on:
  workflow_call:
  pull_request:

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: centos-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

  commitlint:
    name: Check Commit Messages
    runs-on: centos-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://github.com/wagoid/commitlint-github-action/issues/560
      - run: rm tsconfig.json

      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc
          failOnWarnings: true

  check-code-style:
    name: Check Code Style
    needs: dependencies
    runs-on: centos-self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check Code Style
        run: npm run check:code-style

  validate-models:
    name: Validate Models
    needs: dependencies
    runs-on: centos-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Validate Models
        run: npm run validate-models

  check-generated-files:
    name: Check Generated Files
    needs: dependencies
    runs-on: centos-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Generate Files
        run: npm run generate-typescript-types

      - name: Verify Changed Files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files

      - name: Check Changed Files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed(`Changed Files: ${{ steps.verify-changed-files.outputs.changed_files }}`)

  preview-release-notes:
    name: Preview Release Notes
    needs: dependencies
    runs-on: centos-self-hosted
    if: github.event.pull_request.number
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Generate Release Notes Preview
        id: build-release-notes
        uses: guilhermetod/semantic-release-notes-preview@v1.0.0

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: |
            Below is a preview of the release notes if your PR gets merged.

      - name: Comment Release Notes Preview
        if: steps.build-release-notes.outputs.releaseNotes
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ## 👋 Hey there!
            Thank you for you contribution. Below is a preview of the release notes if your PR gets merged.
            Please, make sure it includes all your significant changes with descriptive messages.
            Keep in mind that release notes are automatically generated from the commit messages according to [conventional commits](https://www.conventionalcommits.org/).
            If you feel like you need to change anything, please take a look into [this guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#addressing-review-feedback) to learn how you can fixup your commits.

            ---

            ${{ steps.build-release-notes.outputs.releaseNotes }}
  check-breaking-changes:
    name: Check Breaking Changes
    needs: dependencies
    runs-on: centos-self-hosted
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout Base Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}
          path: './base-branch'

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check Breaking Changes
        id: check-breaking-changes
        shell: bash
        run: npm run check:breaking-changes
        continue-on-error: true

      - name: Check Breaking Change Commit
        if: steps.check-breaking-changes.outcome != 'success'
        uses: ./.github/actions/check-breaking-change-commit
