# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Release

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      HELLO:
        required: true
        type: string
    secrets:
      FOO:
        required: true

jobs:
  # bouncer:
  #   name: Bouncer Inspection
  #   uses: ./.github/workflows/bouncer.yml

  release:
    name: Publish Release
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Echo var (release)
        run: |
          echo "HELLO: ${{ inputs.HELLO }}"

      - name: Echo secret (release)
        run: |
          echo "RELEASE_USER: ${{ secrets.FOO }}"
