name: Execute Job on Non-Master Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        required: true

jobs:
  execute-on-non-master:
    runs-on: ubuntu-latest
    if: github.event.inputs.branch != 'master'
    steps:
      - name: Execute Job on Non-Master Branch
        run: echo "This job runs on a non-master branch."
