name: My Workflow

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: First Step
        if: github.ref_name == 'master'
        run: exit 1

      - name: Next Step
        run: echo "This step will only run if the branch is not master."
