name: Sync Prismic Development

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  release:
    name: Publish Release
    uses: ./.github/workflows/release.yml

  sync-prismic-dev:
    name: Sync Prismic Development Environment
    environment: development
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Sync Prismic
        uses: ./.github/actions/sync-prismic
        with:
          custom-types-api-token: ${{ secrets.CUSTOM_TYPES_API_TOKEN }}
          prismic-repository: ${{ vars.PRISMIC_REPOSITORY }}
