name: Sync Prismic Production

on:
  workflow_dispatch:
  workflow_run:
    workflows: Sync Prismic Production Environment
    types: requested
    branches-ignore: master

jobs:
  sync-prismic-prd:
    name: Sync Prismic Production Environment
    # environment: production
    runs-on: centos-self-hosted
    steps:
      - name: Run Hello World
        run: echo "Hello, World! This is a custom action."

      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Install Dependencies
      #   uses: ./.github/actions/install-dependencies

      # - name: Sync Prismic
      #   uses: ./.github/actions/sync-prismic
      #   with:
      #     custom-types-api-token: ${{ secrets.CUSTOM_TYPES_API_TOKEN }}
      #     prismic-repository: ${{ vars.PRISMIC_REPOSITORY }}
