name: Sync Prismic Development

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  release:
    name: Publish Release
    uses: ./.github/workflows/release.yml
    with:
      HELLO: ${{ vars.HELLO }}
    secrets:
      FOO: ${{ secrets.FOO }}

  sync-prismic-dev:
    name: Sync Prismic Development Environment
    environment: development
    needs: release
    runs-on: ubuntu-latest
    steps:
      # - name: Echo secret (sync)
      #   run: |
      #     echo "RELEASE_USER: ${{ secrets.FOO }}"

      - name: Sync Prismic Dev
        run: echo "Sync prismic dev"
